# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: netflix-app
#   labels:
#     app: netflix-app
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: netflix-app
#   template:
#     metadata:
#       labels:
#         app: netflix-app
#     spec:
#       containers:
#       - name: netflix-app
#         image: nasi101/netflix:latest
#         ports:
#         - containerPort: 80


apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer   # <--- IMPORTANT: Expose LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80          # Port exposed externally
      targetPort: 80    # Port inside container (nginx listens on 80)
